### ISSUE TITLE
PrivateToken: required variable is not present

### ISSUE THREAD

**Issue by mmert1988** [bitrise-steplib/steps-gitlab-status#11]
The new bitrise UI forces you to create a new secret variable when a field in a step is marked as "sensitive". So in order to provide to provide my GitLab private token, I created one and used it in the step, but this doesn't work apparently and I get following error message in the logs:

Error: failed to parse config:
- PrivateToken: required variable is not present

**Comment by bitce** [comment]
@mmert1988 Sorry to hear about the issue, can you please include a build URL?

**Comment by mmert1988** [comment]
@bitce, for sure:
https://app.bitrise.io/build/045efe6cbdd1b93f

**Comment by bitce** [comment]
Hmm, strange, the actual error I'm seeing here is `Error: server error: 404 Not Found`

Could you also send us an URL where the same configuration worked?

**Comment by mmert1988** [comment]
Hi @bitce, sorry, in the build I just sent above was the error bit different, because I managed somehow to solve the original error by enabling the option `exposable for pull requests` for the secret variable I created for Gitlab Token. But then I got that `Error: server error: 404 Not Found`. Here is a build with the original problem `PrivateToken: required variable is not present`:
https://app.bitrise.io/build/d034130f6b47baa5

I have unfortunately no build for which the Gitlab status step worked...

**Comment by fehersanyi-bitrise** [comment]
Hello @mmert1988!

How did you define the private token for the step?
can You please enable support user so I can check out the configs?

and please make sure that the secret is open for PR-s please, that could be the problem at second guess!

**Comment by mmert1988** [comment]
Hi @fehersanyi-bitrise,

This is how i defined the secret variable:
<img width="1387" alt="screen shot 2018-12-20 at 16 51 55" src="https://user-images.githubusercontent.com/1854117/50295141-b5d89480-0477-11e9-9ae6-af3c6a4b4b92.png">

And this how I configured it in the step:
<img width="1039" alt="screen shot 2018-12-20 at 16 55 43" src="https://user-images.githubusercontent.com/1854117/50295522-7e1e1c80-0478-11e9-89d0-1f7d9306fae5.png">

I left everything else in the step configuration as default. I used version 0.9.4.

So, making the secret open for Pull Requests doesn't solve the problem, unfortunately.

**Comment by fehersanyi-bitrise** [comment]
Hy @mmert1988!

this is strange you set it up correctly, the only off thing I see is the api base url 🤔 it should be gitlab.example.com/api/v4 not git.example.com/api/v4 i think, but it should throw a different error then 😕
anyways, is this still occurring at all?

**Comment by mmert1988** [comment]
Hi @fehersanyi-bitrise,

Yes, unfortunately, it is still occurring. No, the URL is correct. I already tested the API calls in my browser (for example https://git.dev.eon.com/api/v4/projects/2686?private_token=xxxxxx) and it worked!

I also tried to provide the direct path to the project - https://git.dev.eon.com/api/v4/projects/2686 - but still not working...

**Comment by mmert1988** [comment]
Btw, I just tried following GitLab API with Postman for my project, and requests there worked:
https://docs.gitlab.com/ce/api/commits.html#post-the-build-status-to-a-commit

**Comment by wolfAle** [comment]
Hi guys,

I'm experiencing the same issue, with these settings:
- PrivateToken: xxxxx
- RepositoryURL: https://gitlab.mycompany.it/mobile/repo.git
- CommitHash: xxxxxxx
- APIURL: https://gitlab.mycompany.it/api/v4
- Status: running
- TargetURL: https://app.bitrise.io/build/sdasdasdasdas
- Context: Bitrise
- Description: 
Error: server error: 404 Not Found

Any hint about this?

EDIT
Adding some info here: I'm pretty sure that with version 0.9.2 it was working, but I tested again today and it doesn't work either.
Following @mmert1988 url with GitLap API it looks like the url must contain the repo's id (in my case 1025), not sure if the plugin does that. It would be helpful to see the invoked url in the Bitrise logs, to help with debugging.

**Comment by bitce** [comment]
Hi guys! Sorry for the delay, we have an ongoing issue to the step and these issues you have reported were caused by it, unfortunately. We should be fixing this shortly, will update this thread once we're done!

**Comment by mecid** [comment]
@bitce is it already fixed?

**Comment by fehersanyi-bitrise** [comment]
@mecid Hello I guess it is fixed, make sure that the secret is enabled for PR builds.

**Comment by mecid** [comment]
@bitce still have it for PR builds.

**Comment by fehersanyi-bitrise** [comment]
@mecid is that switch turned on?
<img width="194" alt="Screenshot 2019-04-01 at 14 33 01" src="https://user-images.githubusercontent.com/43136024/55327746-128e1700-548b-11e9-9b29-7d73832234c2.png">

**Comment by mecid** [comment]
@bitce It helps, thank you!

**Comment by fehersanyi-bitrise** [comment]
I'm glad to hear it works!

**Comment by pmegremis** [comment]
Hi guys,
One thing that is unclear to me is if i have to include project id in APIURL?
Which is the correct one?
https://gitlab.mycompany.it/api/v4
or
https://gitlab.mycompany.it/api/v4/projects/1234

**Comment by Roland-Bak** [comment]
Hi @pmegremis!

You don't actually have to include the project id in API URL, the correct input would be https://gitlab.example.com/api/v4  🙂

**Comment by rocooshiang** [comment]
I have a problem in gitlab-status steps, as following error message.

+------------------------------------------------------------------------------+

| (0) gitlab-status@0.9.6                                                      |
+------------------------------------------------------------------------------+
| id: gitlab-status                                                            |
| version: 0.9.6                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2019-10-16T07:32:31Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
GitLab requires a commit hash for build status reporting
WARN[07:32:37] Step (gitlab-status@0.9.6) failed, but was marked as skippable 
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ! | gitlab-status@0.9.6 (exit code: 1)                            | 7.83 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: https://github.com/bitrise-steplib/steps-gitlab-status/issues |
| Source: https://github.com/bitrise-steplib/steps-gitlab-status               |
+---+---------------------------------------------------------------+----------+

I

**Comment by bitce** [comment]
Hi @rocooshiang! Have you provided the API token the step needs? If so, is it a PR build and is the secret exposed for PRs? :)

**Comment by ivanstnsk** [comment]
Yesterday was working fine. Today I'm getting the same error:
+------------------------------------------------------------------------------+

| (1) gitlab-status@0                                                          |
+------------------------------------------------------------------------------+
| id: gitlab-status                                                            |
| version: 0.12.1                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2020-06-03T09:27:06Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
Error: failed to parse config:
- PrivateToken: required variable is not present

**Nothing was changed**

**Comment by istx25** [comment]
Hi @ivanstnsk,

Can you please share a build link and enable support access in project settings?
