### ISSUE TITLE
Subgroups are not handled

### ISSUE THREAD

**Issue by abarisain** [bitrise-steplib/steps-gitlab-status#19]
Hi,

Our org switched to subgroups, and this step doesn't support them.

This regexp is the culprit: https://github.com/bitrise-steplib/steps-gitlab-status/blob/master/main.go#L30-L36

Our URL look like this:

`https://gitlab.foobar.com/group/subgroup/repo.git` , and the resulting status URL is 
`https://gitlab.foobar.com/api/v4/projects/subgroup%2Frepo/statuses/<hash>`

I'm not sure what's the best way to handle this. I would not mind an environment variable that doesn't attempt to parse an url, but simply expects "group/subgroup/repo" to be well formed.

**Comment by palcalde** [comment]
Hi, we have the same problem, we are experiencing this error 

![image](https://user-images.githubusercontent.com/1252619/78040674-0d023000-7370-11ea-912c-0197def74190.png)


`Error: server error: 404 Not Found url: https://gitlab.otters.xyz/api/v4/projects/apps%2Fios/statuses/47dca99839a08f33c1aad37e9114426ca992364d code: 404 body: {"message":"404 Project Not Found"}
`

As you can see the URL does not contain the project ID but instead the group/subgroup of the gitlab path.

This worked well until 2 weeks ago, I think is this change what broke it: https://github.com/bitrise-steplib/steps-gitlab-status/commit/222f187ee5a12b3523709a9e92bc2d0fcaf4896d

**Comment by palcalde** [comment]
@trapacska could you give us some help here? it seems you recently changed that method.

**Comment by palcalde** [comment]
@abarisain I was able to make it work again with version 9

**Comment by abarisain** [comment]
thanks!

**Comment by garciadiegosebastian** [comment]
Please, can you fix this error? It is a real big bug!

**Comment by garciadiegosebastian** [comment]
@trapacska Please, could you help us with this?

**Comment by mackoj** [comment]
I have this issue too I add some test to prove it https://github.com/bitrise-steplib/steps-gitlab-status/pull/21

**Comment by usmonster** [comment]
I believe I've fixed it in #22. Trying to get the attention of a maintainer.

**Comment by istx25** [comment]
We have a ticket for this and will follow-up as soon as it has been fixed. Thank you.

**Comment by usmonster** [comment]
Hi @non-binary! Do you refer to an internal ticket? Can you please check out the fix I've already provided in #22 and comment if you see anything missing? I believe the fastest path to fixing it would be to merge and release the changes in that PR. Thanks!

**Comment by istx25** [comment]
@usmonster Yes, I mean an internal ticket. I am support so I don't have decision power of using that pull request or not but I will send it over to the engineering team to review.

**Comment by usmonster** [comment]
Thank you! I'm happy as long as someone can look at it. :)
