### ISSUE TITLE
Add name and description option to config

### ISSUE THREAD

**Issue by micsco** [bitrise-steplib/steps-gitlab-status#2]
Thanks for this!

One feature improvement I'd love to see is the ability to set the name and/or description of the build status.

As a default I think this should be bitrise:[project title]

**Comment by viktorbenei** [comment]
Thanks for the feature request @micsco ! :) Feel free to send a PR if you have some time ;)

**Comment by micsco** [comment]
In the process of learning Go so that I can!

**Comment by viktorbenei** [comment]
Let us know if you'd have any questions! ;)

**Comment by viktorbenei** [comment]
Or @kdobmayer should we wait with this, until the refactor? Any show stoppers?

**Comment by micsco** [comment]
Fixed in #6

**Comment by viktorbenei** [comment]
Thanks for opening this issue @micsco ! :)
