### ISSUE TITLE
Aborted builds

### ISSUE THREAD

**Issue by AlbertMontserrat** [bitrise-steplib/steps-gitlab-status#26]
Hello,

I would like to know if we can run this step if the build has been aborted.

This step is only checking success or failure in auto status, and it's not running if the build have been aborted.

Thanks

**Comment by istx25** [comment]
If a build has been aborted, it stops running at the point in which you cancel the build so the only way to have this run is put it sooner in the workflow or wait until it has completed before aborting the build.
