### ISSUE TITLE
Set target_url to the bitrise build url

### ISSUE THREAD

**Issue by micsco** [bitrise-steplib/steps-gitlab-status#3]
Gitlab allows you to define the target_url for the status, this should be set to the build page.

**Comment by viktorbenei** [comment]
Definitely! Thanks for the feature request @micsco ! ;)

**Comment by micsco** [comment]
Fixed in #6, thanks!

**Comment by viktorbenei** [comment]
Thanks for creating the issue @micsco ! ;)
